---

- name: Configure ElasticSearch
  hosts: moloch
  roles:
    - { role: elasticsearch, elasticsearch_network_host: '0.0.0.0', elasticsearch_http_port: '9200'}

- name: Configure Moloch
  hosts: moloch
  roles:
    - { role: ruby }
    - { role: moloch }

- name: Install glance
  hosts: elk
  tasks:

    - apt:
        name: glance

- name: Install netdata
  hosts: elk
  tasks:

    - apt:
        name: netdata
