- name: Install/Setup Nginx
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Backup nginx conf
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    state: directory

- file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0400

- name: Copy nginx.conf
  template:
    src: files/nginx/nginx.conf
    dest:  /etc/nginx/nginx.conf

- name: Copy nginx_moloch.conf
  template:
    src: templates/nginx_moloch.conf
    dest: /etc/nginx/sites-available/nginx_moloch.conf

- name: Make symlink to sites-enabled
  file:
    src: /etc/nginx/sites-available/nginx_moloch.conf
    dest: /etc/nginx/sites-enabled/nginx_moloch.conf
    state: link

- name: Start Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes
